name: smart_waste_segregation
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  http: ^1.2.1
  google_fonts: ^6.3.0
  provider: ^6.1.5+1
  firebase_core: ^2.32.0
  go_router: ^16.2.4
  camera: ^0.11.0+1
  firebase_auth: ^4.20.0
  flutter_map: ^8.2.2
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
